# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ComapeoMapBuilder
                                 A QGIS plugin
 Generates SMP files for CoMapeo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-01
        copyright            : (C) 2025 by Awana Digital
        email                : luandro@awana.digital
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Awana Digital'
__date__ = '2025-05-01'
__copyright__ = '(C) 2025 by Awana Digital'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ComapeoMapBuilder class from file ComapeoMapBuilder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .comapeo_smp import ComapeoMapBuilderPlugin
    return ComapeoMapBuilderPlugin()
