# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ComapeoMapBuilder
                                 A QGIS plugin
 Generates SMP files for CoMapeo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-01
        copyright            : (C) 2025 by Awana Digital
        email                : luandro@awana.digital
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is released under the MIT License.                       *
 *   Copyright (c) 2026 Awana Digital                                      *
 *   See LICENSE for full license text.                                    *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Awana Digital'
__date__ = '2025-05-01'
__copyright__ = '(C) 2025 by Awana Digital'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.core import QgsApplication
from .comapeo_smp_provider import ComapeoMapBuilderProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class ComapeoMapBuilderPlugin(object):

    def __init__(self):
        self.provider = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        if self.provider is not None:
            return  # guard against duplicate initialisation
        provider = ComapeoMapBuilderProvider()
        if QgsApplication.processingRegistry().addProvider(provider):
            self.provider = provider

    def initGui(self):
        self.initProcessing()

    def unload(self):
        if self.provider is not None:
            removed = QgsApplication.processingRegistry().removeProvider(self.provider)
            if removed:
                self.provider = None
