# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ComapeoMapBuilder
                                 A QGIS plugin
 Generates SMP files for CoMapeo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-01
        copyright            : (C) 2025 by Awana Digital
        email                : luandro@awana.digital
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is released under the MIT License.                       *
 *   Copyright (c) 2026 Awana Digital                                      *
 *   See LICENSE for full license text.                                    *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Awana Digital'
__date__ = '2025-05-01'
__copyright__ = '(C) 2025 by Awana Digital'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os

from qgis.PyQt.QtCore import QCoreApplication, QStandardPaths
from qgis.core import (QgsProcessingAlgorithm,
                       QgsProcessingParameterExtent,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingParameterBoolean,
                       QgsProcessingException,
                       QgsProject)

from .comapeo_smp_generator import SMPGenerator


class ComapeoMapBuilderAlgorithm(QgsProcessingAlgorithm):
    """
    This algorithm generates SMP files for CoMapeo.

    It takes a vector layer as input and allows you to specify:
    - The extent of the area to export
    - The minimum zoom level
    - The maximum zoom level
    - The tile image format (PNG or JPG)
    - The JPEG quality (when JPG is selected)

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    EXTENT = 'EXTENT'
    MIN_ZOOM = 'MIN_ZOOM'
    MAX_ZOOM = 'MAX_ZOOM'
    TILE_FORMAT = 'TILE_FORMAT'
    JPEG_QUALITY = 'JPEG_QUALITY'
    OUTPUT_FILE = 'OUTPUT_FILE'
    INCLUDE_WORLD_BASE_ZOOMS = 'INCLUDE_WORLD_BASE_ZOOMS'
    WORLD_MAX_ZOOM = 'WORLD_MAX_ZOOM'
    INCLUDE_REGION = 'INCLUDE_REGION'
    REGION_EXTENT = 'REGION_EXTENT'
    REGION_MIN_ZOOM = 'REGION_MIN_ZOOM'
    REGION_MAX_ZOOM = 'REGION_MAX_ZOOM'

    # Tile format options presented to the user
    TILE_FORMAT_OPTIONS = ['PNG', 'JPG', 'WEBP']

    @classmethod
    def default_tile_format_index(cls):
        """Return the default tile format enum index for the current runtime."""
        preferred_formats = [
            SMPGenerator.TILE_FORMAT_WEBP,
            SMPGenerator.TILE_FORMAT_JPG,
            SMPGenerator.TILE_FORMAT_PNG,
        ]
        for tile_format in preferred_formats:
            if SMPGenerator.is_tile_format_supported(tile_format):
                return cls.TILE_FORMAT_OPTIONS.index(tile_format)
        return cls.TILE_FORMAT_OPTIONS.index(SMPGenerator.TILE_FORMAT_PNG)

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # Add extent parameter
        self.addParameter(
            QgsProcessingParameterExtent(
                self.EXTENT,
                self.tr('Extent'),
                optional=False
            )
        )

        # Add min zoom parameter
        self.addParameter(
            QgsProcessingParameterNumber(
                self.MIN_ZOOM,
                self.tr('Minimum zoom level'),
                QgsProcessingParameterNumber.Integer,
                defaultValue=0,
                optional=False,
                minValue=0,
                maxValue=24
            )
        )

        # Add max zoom parameter
        self.addParameter(
            QgsProcessingParameterNumber(
                self.MAX_ZOOM,
                self.tr('Maximum zoom level'),
                QgsProcessingParameterNumber.Integer,
                defaultValue=14,
                optional=False,
                minValue=0,
                maxValue=24
            )
        )

        # Add tile format parameter (PNG / JPG / WEBP)
        self.addParameter(
            QgsProcessingParameterEnum(
                self.TILE_FORMAT,
                self.tr('Tile image format'),
                options=self.TILE_FORMAT_OPTIONS,
                defaultValue=self.default_tile_format_index(),
                optional=False
            )
        )

        # Add JPEG quality parameter (only meaningful when JPG is selected)
        jpeg_quality_param = QgsProcessingParameterNumber(
            self.JPEG_QUALITY,
            self.tr('JPEG/WebP quality (1-100, used when format is JPG or WEBP)'),
            QgsProcessingParameterNumber.Integer,
            defaultValue=85,
            optional=True,
            minValue=1,
            maxValue=100
        )
        self.addParameter(jpeg_quality_param)

        self.addParameter(
            QgsProcessingParameterBoolean(
                self.INCLUDE_WORLD_BASE_ZOOMS,
                self.tr('Include World overview source'),
                defaultValue=True,
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.WORLD_MAX_ZOOM,
                self.tr('World maximum zoom'),
                QgsProcessingParameterNumber.Integer,
                defaultValue=3,
                optional=False,
                minValue=0,
                maxValue=24
            )
        )

        self.addParameter(
            QgsProcessingParameterBoolean(
                self.INCLUDE_REGION,
                self.tr('Include Region detail source'),
                defaultValue=False,
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterExtent(
                self.REGION_EXTENT,
                self.tr('Region extent'),
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.REGION_MIN_ZOOM,
                self.tr('Region minimum zoom level'),
                QgsProcessingParameterNumber.Integer,
                defaultValue=6,
                optional=True,
                minValue=0,
                maxValue=24
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.REGION_MAX_ZOOM,
                self.tr('Region maximum zoom level'),
                QgsProcessingParameterNumber.Integer,
                defaultValue=9,
                optional=True,
                minValue=0,
                maxValue=24
            )
        )

        # Add output file parameter
        # Default to project title, then filename, otherwise 'output'
        project = QgsProject.instance()
        project_name = ''
        if project:
            title = project.title()
            if isinstance(title, str) and title.strip():
                project_name = title
            else:
                base = project.baseName()
                if isinstance(base, str) and base.strip():
                    project_name = base
        if not project_name:
            base_name = 'output'
        else:
            # Sanitize: replace spaces and special chars
            base_name = ''.join(
                c if c.isalnum() or c in '-_' else '_'
                for c in project_name
            ).rstrip('_')
            if not base_name:
                base_name = 'output'

        # Prefer project directory; fall back to OS Documents folder
        project_path = QgsProject.instance().fileName()
        if project_path:
            default_dir = os.path.dirname(project_path)
        else:
            default_dir = QStandardPaths.writableLocation(
                QStandardPaths.DocumentsLocation
            )
        default_output = os.path.join(default_dir, base_name + '.smp')

        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT_FILE,
                self.tr('Output SMP file'),
                fileFilter='SMP files (*.smp)',
                defaultValue=default_output
            )
        )

    def _region_extent_value(self, parameters, context):
        """Return the optional Region extent or None when unset."""
        region_extent = self.parameterAsExtent(parameters, self.REGION_EXTENT, context)
        if region_extent is None or region_extent.isEmpty():
            return None
        return region_extent

    def _source_configuration(self, parameters, context):
        """Extract fixed world/region/local configuration from Processing parameters."""
        include_world_base_zooms = self.parameterAsBool(
            parameters, self.INCLUDE_WORLD_BASE_ZOOMS, context
        )
        include_region = self.parameterAsBool(parameters, self.INCLUDE_REGION, context)

        return {
            'include_world_base_zooms': include_world_base_zooms,
            'world_max_zoom': self.parameterAsInt(parameters, self.WORLD_MAX_ZOOM, context),
            'include_region': include_region,
            'region_extent': self._region_extent_value(parameters, context) if include_region else None,
            'region_min_zoom': (
                self.parameterAsInt(parameters, self.REGION_MIN_ZOOM, context)
                if include_region else None
            ),
            'region_max_zoom': (
                self.parameterAsInt(parameters, self.REGION_MAX_ZOOM, context)
                if include_region else None
            ),
        }

    def checkParameterValues(self, parameters, context):
        """
        Pre-flight validation called when the user clicks Run in the Processing dialog.
        Returning (False, msg) blocks execution and shows msg as an error in the dialog.
        This gives immediate feedback before the dialog closes, unlike processAlgorithm()
        which only reports errors after the run has started.
        """
        # Let QGIS validate basic parameter types first
        ok, msg = super().checkParameterValues(parameters, context)
        if not ok:
            return ok, msg

        # Zoom range ordering
        min_zoom = self.parameterAsInt(parameters, self.MIN_ZOOM, context)
        max_zoom = self.parameterAsInt(parameters, self.MAX_ZOOM, context)
        if min_zoom > max_zoom:
            return False, self.tr(
                'Minimum zoom level ({}) must not exceed maximum zoom level ({}).'.format(
                    min_zoom, max_zoom)
            )

        fixed_source_options = self._source_configuration(parameters, context)

        # Retrieve extent — if unset, let processAlgorithm handle it
        extent = self.parameterAsExtent(parameters, self.EXTENT, context)
        if extent is None or extent.isEmpty():
            return True, ''

        # Tile format is only needed for disk-space estimation. Validate the
        # fixed source model first so users see source/zoom errors before any
        # unrelated output-format issues.
        tile_format = None
        generator = SMPGenerator()

        try:
            export_plan = generator._build_export_plan(
                extent,
                min_zoom,
                max_zoom,
                **fixed_source_options
            )
        except ValueError as exc:
            return False, self.tr(str(exc))

        tile_count = export_plan['total_tiles']

        # Block if the output drive has insufficient space
        output_file = self.parameterAsFileOutput(parameters, self.OUTPUT_FILE, context)
        if output_file:
            tile_format_index = self.parameterAsEnum(parameters, self.TILE_FORMAT, context)
            if not isinstance(tile_format_index, int):
                return False, self.tr(
                    'Invalid tile format value: {}'.format(tile_format_index)
                )
            if tile_format_index < 0 or tile_format_index >= len(self.TILE_FORMAT_OPTIONS):
                return False, self.tr(
                    'Invalid tile format index: {}'.format(tile_format_index)
                )
            tile_format = self.TILE_FORMAT_OPTIONS[tile_format_index]
            try:
                tile_format = SMPGenerator.validate_tile_format(tile_format)
            except ValueError as exc:
                return False, self.tr(str(exc))
            try:
                generator.validate_disk_space(output_file, tile_count, tile_format)
            except OSError as exc:
                return False, str(exc)

        return True, ''

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Get the extent parameter
        extent = self.parameterAsExtent(parameters, self.EXTENT, context)

        # Get the min and max zoom parameters
        min_zoom = self.parameterAsInt(parameters, self.MIN_ZOOM, context)
        max_zoom = self.parameterAsInt(parameters, self.MAX_ZOOM, context)

        fixed_source_options = self._source_configuration(parameters, context)

        # Get tile format
        tile_format_index = self.parameterAsEnum(parameters, self.TILE_FORMAT, context)
        if not isinstance(tile_format_index, int):
            raise QgsProcessingException(
                self.tr('Invalid tile format value: {}'.format(tile_format_index))
            )
        if tile_format_index < 0 or tile_format_index >= len(self.TILE_FORMAT_OPTIONS):
            raise QgsProcessingException(
                self.tr('Invalid tile format index: {}'.format(tile_format_index))
            )
        tile_format = self.TILE_FORMAT_OPTIONS[tile_format_index]
        try:
            tile_format = SMPGenerator.validate_tile_format(tile_format)
        except ValueError as exc:
            raise QgsProcessingException(self.tr(str(exc)))

        # Get JPEG quality
        jpeg_quality = self.parameterAsInt(parameters, self.JPEG_QUALITY, context)
        if jpeg_quality is None or jpeg_quality <= 0:
            jpeg_quality = 85

        # Get the output file path
        output_file = self.parameterAsFileOutput(parameters, self.OUTPUT_FILE, context)

        # Validate zoom range
        if min_zoom > max_zoom:
            raise QgsProcessingException(
                self.tr('Minimum zoom level must be less than or equal to maximum zoom level.')
            )

        generator = SMPGenerator(feedback)

        try:
            export_plan = generator._build_export_plan(
                extent,
                min_zoom,
                max_zoom,
                **fixed_source_options
            )
        except ValueError as exc:
            raise QgsProcessingException(self.tr(str(exc)))

        feedback.pushInfo(
            self.tr('Using visible project layers in layer-tree order for rendering')
        )
        feedback.pushInfo(self.tr(f'Extent: {extent.asWktPolygon()}'))
        feedback.pushInfo(self.tr(f'Min zoom: {min_zoom}'))
        feedback.pushInfo(self.tr(f'Max zoom: {max_zoom}'))
        feedback.pushInfo(self.tr(f'Tile format: {tile_format}'))
        feedback.pushInfo(self.tr(f'Include world source: {fixed_source_options["include_world_base_zooms"]}'))
        feedback.pushInfo(self.tr(f'World max zoom: {fixed_source_options["world_max_zoom"]}'))
        feedback.pushInfo(self.tr(f'Include region source: {fixed_source_options["include_region"]}'))
        if fixed_source_options['include_region'] and fixed_source_options['region_extent'] is not None:
            feedback.pushInfo(
                self.tr(f'Region extent: {fixed_source_options["region_extent"].asWktPolygon()}')
            )
            feedback.pushInfo(
                self.tr(
                    f'Region zoom range: '
                    f'{fixed_source_options["region_min_zoom"]}-{fixed_source_options["region_max_zoom"]}'
                )
            )
        if tile_format in ('JPG', 'WEBP'):
            feedback.pushInfo(self.tr(f'{tile_format} quality: {jpeg_quality}'))
        feedback.pushInfo(self.tr(f'Output file: {output_file}'))

        estimated_tiles = export_plan['total_tiles']
        world_coverage_tiles = export_plan['world_coverage_tiles']
        estimated_bytes = generator.estimate_tile_storage_bytes(estimated_tiles, tile_format)
        estimated_mb = estimated_bytes / (1024 * 1024)
        feedback.pushInfo(self.tr(f'Estimated tile count: {estimated_tiles:,}'))
        feedback.pushInfo(self.tr(f'Estimated size: {estimated_mb:.1f} MB'))
        feedback.pushInfo(
            self.tr(
                'Estimated world pyramid coverage: {:.2f}% ({:,}/{:,} tiles)'.format(
                    export_plan['world_pct'],
                    world_coverage_tiles,
                    export_plan['world_tiles']
                )
            )
        )
        if export_plan['gap_zooms']:
            feedback.reportError(
                self.tr(
                    'No raster coverage will be generated for zoom levels: {}'.format(
                        ', '.join(str(zoom) for zoom in export_plan['gap_zooms'])
                    )
                ),
                fatalError=False
            )

        # Generate the SMP file
        try:
            output_path = generator.generate_smp_from_canvas(
                extent, min_zoom, max_zoom, output_file,
                tile_format=tile_format, jpeg_quality=jpeg_quality,
                include_world_base_zooms=fixed_source_options['include_world_base_zooms'],
                world_max_zoom=fixed_source_options['world_max_zoom'],
                include_region=fixed_source_options['include_region'],
                region_extent=fixed_source_options['region_extent'],
                region_min_zoom=fixed_source_options['region_min_zoom'],
                region_max_zoom=fixed_source_options['region_max_zoom'],
                export_plan=export_plan
            )
        except (ValueError, OSError) as exc:
            raise QgsProcessingException(str(exc))

        # generate_smp_from_canvas returns None when the user cancelled.
        # Return an empty result dict so Processing surfaces it as cancelled,
        # not as a successful run with an empty output.
        if output_path is None:
            return {}

        # Return the results
        return {self.OUTPUT_FILE: output_path}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'generatesmp'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('Generate SMP Map')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'smp'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return ComapeoMapBuilderAlgorithm()
