# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ComapeoMapBuilder
                                 A QGIS plugin
 Generates SMP files for CoMapeo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-01
        copyright            : (C) 2025 by Awana Digital
        email                : luandro@awana.digital
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is released under the MIT License.                       *
 *   Copyright (c) 2026 Awana Digital                                      *
 *   See LICENSE for full license text.                                    *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Awana Digital'
__date__ = '2025-05-01'
__copyright__ = '(C) 2025 by Awana Digital'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os

from qgis.PyQt.QtCore import QCoreApplication, QStandardPaths
from qgis.core import (QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterMultipleLayers,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingException)

from .comapeo_smp_merger import merge_smp_files


class ComapeoSmpMergeAlgorithm(QgsProcessingAlgorithm):
    """Processing algorithm that merges two or more SMP files into one.

    Users select multiple ``.smp`` files as input and specify an output
    path. The algorithm delegates all heavy lifting to
    :func:`merge_smp_files`.
    """

    INPUT_FILES = 'INPUT_FILES'
    OUTPUT_FILE = 'OUTPUT_FILE'

    def initAlgorithm(self, config):
        """Define the input and output parameters."""
        input_param = QgsProcessingParameterMultipleLayers(
            self.INPUT_FILES,
            self.tr('Input SMP files'),
            QgsProcessing.TypeFile,
            optional=False
        )
        input_param.setMinimumNumberInputs(2)
        self.addParameter(input_param)

        # Default output path
        default_dir = QStandardPaths.writableLocation(
            QStandardPaths.DocumentsLocation
        )
        default_output = os.path.join(default_dir, 'merged.smp')

        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT_FILE,
                self.tr('Output merged SMP file'),
                fileFilter='SMP files (*.smp)',
                defaultValue=default_output
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """Execute the merge."""
        input_paths = [
            str(path).strip()
            for path in self.parameterAsFileList(
                parameters, self.INPUT_FILES, context
            )
            if str(path).strip()
        ]

        if len(input_paths) < 2:
            raise QgsProcessingException(
                self.tr(
                    'At least 2 SMP files are required for merging.'
                )
            )

        for path in input_paths:
            if not path.lower().endswith('.smp'):
                raise QgsProcessingException(
                    self.tr(
                        'Input file is not an SMP archive: {}'.format(path)
                    )
                )
            if not os.path.isfile(path):
                raise QgsProcessingException(
                    self.tr(
                        'Input file does not exist: {}'.format(path)
                    )
                )

        output_file = self.parameterAsFileOutput(
            parameters, self.OUTPUT_FILE, context
        )

        feedback.pushInfo(
            self.tr('Merging {} SMP files...'.format(len(input_paths)))
        )

        try:
            result = merge_smp_files(input_paths, output_file,
                                     feedback=feedback)
        except ValueError as exc:
            raise QgsProcessingException(self.tr(str(exc)))
        except OSError as exc:
            raise QgsProcessingException(str(exc))

        if result is None:
            return {}

        return {self.OUTPUT_FILE: result}

    def name(self):
        """Return the algorithm name."""
        return 'mergesmp'

    def displayName(self):
        """Return the translated algorithm name."""
        return self.tr('Merge SMP Files')

    def group(self):
        """Return the group name."""
        return self.tr(self.groupId())

    def groupId(self):
        """Return the group ID."""
        return 'smp'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return ComapeoSmpMergeAlgorithm()
