# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ComapeoMapBuilder
                                 A QGIS plugin
 Generates SMP files for CoMapeo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-01
        copyright            : (C) 2025 by Awana Digital
        email                : luandro@awana.digital
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Awana Digital'
__date__ = '2025-05-01'
__copyright__ = '(C) 2025 by Awana Digital'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessingAlgorithm,
                       QgsProcessingParameterExtent,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingException,
                       QgsRectangle)

from .comapeo_smp_generator import SMPGenerator


class ComapeoMapBuilderAlgorithm(QgsProcessingAlgorithm):
    """
    This algorithm generates SMP files for CoMapeo.

    It takes a vector layer as input and allows you to specify:
    - The extent of the area to export
    - The minimum zoom level
    - The maximum zoom level
    - The tile image format (PNG or JPG)
    - The JPEG quality (when JPG is selected)

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    EXTENT = 'EXTENT'
    MIN_ZOOM = 'MIN_ZOOM'
    MAX_ZOOM = 'MAX_ZOOM'
    TILE_FORMAT = 'TILE_FORMAT'
    JPEG_QUALITY = 'JPEG_QUALITY'
    OUTPUT_FILE = 'OUTPUT_FILE'

    # Tile format options presented to the user
    TILE_FORMAT_OPTIONS = ['PNG', 'JPG']

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # Add extent parameter
        self.addParameter(
            QgsProcessingParameterExtent(
                self.EXTENT,
                self.tr('Extent'),
                optional=False
            )
        )

        # Add min zoom parameter
        self.addParameter(
            QgsProcessingParameterNumber(
                self.MIN_ZOOM,
                self.tr('Minimum zoom level'),
                QgsProcessingParameterNumber.Integer,
                defaultValue=0,
                optional=False,
                minValue=0,
                maxValue=24
            )
        )

        # Add max zoom parameter
        self.addParameter(
            QgsProcessingParameterNumber(
                self.MAX_ZOOM,
                self.tr('Maximum zoom level'),
                QgsProcessingParameterNumber.Integer,
                defaultValue=14,
                optional=False,
                minValue=0,
                maxValue=24
            )
        )

        # Add tile format parameter (PNG / JPG)
        self.addParameter(
            QgsProcessingParameterEnum(
                self.TILE_FORMAT,
                self.tr('Tile image format'),
                options=self.TILE_FORMAT_OPTIONS,
                defaultValue=1,  # JPG
                optional=False
            )
        )

        # Add JPEG quality parameter (only meaningful when JPG is selected)
        jpeg_quality_param = QgsProcessingParameterNumber(
            self.JPEG_QUALITY,
            self.tr('JPEG quality (1-100, only used when format is JPG)'),
            QgsProcessingParameterNumber.Integer,
            defaultValue=85,
            optional=True,
            minValue=1,
            maxValue=100
        )
        self.addParameter(jpeg_quality_param)

        # Add output file parameter
        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT_FILE,
                self.tr('Output SMP file'),
                fileFilter='SMP files (*.smp)'
            )
        )

    def checkParameterValues(self, parameters, context):
        """
        Pre-flight validation called when the user clicks Run in the Processing dialog.
        Returning (False, msg) blocks execution and shows msg as an error in the dialog.
        This gives immediate feedback before the dialog closes, unlike processAlgorithm()
        which only reports errors after the run has started.
        """
        # Let QGIS validate basic parameter types first
        ok, msg = super().checkParameterValues(parameters, context)
        if not ok:
            return ok, msg

        # Zoom range ordering
        min_zoom = self.parameterAsInt(parameters, self.MIN_ZOOM, context)
        max_zoom = self.parameterAsInt(parameters, self.MAX_ZOOM, context)
        if min_zoom > max_zoom:
            return False, self.tr(
                'Minimum zoom level ({}) must not exceed maximum zoom level ({}).'.format(
                    min_zoom, max_zoom)
            )

        # Retrieve extent — if unset, let processAlgorithm handle it
        extent = self.parameterAsExtent(parameters, self.EXTENT, context)
        if extent is None or extent.isEmpty():
            return True, ''

        # Tile format (needed for disk-space estimate)
        tile_format_index = self.parameterAsEnum(parameters, self.TILE_FORMAT, context)
        if tile_format_index < 0 or tile_format_index >= len(self.TILE_FORMAT_OPTIONS):
            return False, self.tr(
                'Invalid tile format index: {}'.format(tile_format_index)
            )
        tile_format = self.TILE_FORMAT_OPTIONS[tile_format_index]

        # Instantiate generator without feedback (logs go to QgsMessageLog only)
        generator = SMPGenerator()

        tile_count, _warning = generator.validate_tile_count(extent, min_zoom, max_zoom)

        # Block if the output drive has insufficient space
        output_file = self.parameterAsFileOutput(parameters, self.OUTPUT_FILE, context)
        if output_file:
            try:
                generator.validate_disk_space(output_file, tile_count, tile_format)
            except OSError as exc:
                return False, str(exc)

        return True, ''

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Get the extent parameter
        extent = self.parameterAsExtent(parameters, self.EXTENT, context)

        # Get the min and max zoom parameters
        min_zoom = self.parameterAsInt(parameters, self.MIN_ZOOM, context)
        max_zoom = self.parameterAsInt(parameters, self.MAX_ZOOM, context)

        # Get tile format
        tile_format_index = self.parameterAsEnum(parameters, self.TILE_FORMAT, context)
        if tile_format_index < 0 or tile_format_index >= len(self.TILE_FORMAT_OPTIONS):
            raise QgsProcessingException(
                self.tr('Invalid tile format index: {}'.format(tile_format_index))
            )
        tile_format = self.TILE_FORMAT_OPTIONS[tile_format_index]

        # Get JPEG quality
        jpeg_quality = self.parameterAsInt(parameters, self.JPEG_QUALITY, context)
        if jpeg_quality is None or jpeg_quality <= 0:
            jpeg_quality = 85

        # Get the output file path
        output_file = self.parameterAsFileOutput(parameters, self.OUTPUT_FILE, context)

        # Validate zoom range
        if min_zoom > max_zoom:
            raise QgsProcessingException(
                self.tr('Minimum zoom level must be less than or equal to maximum zoom level.')
            )

        # Log the parameters for debugging
        feedback.pushInfo(self.tr('Using all visible layers from the current map canvas'))
        feedback.pushInfo(self.tr(f'Extent: {extent.asWktPolygon()}'))
        feedback.pushInfo(self.tr(f'Min zoom: {min_zoom}'))
        feedback.pushInfo(self.tr(f'Max zoom: {max_zoom}'))
        feedback.pushInfo(self.tr(f'Tile format: {tile_format}'))
        if tile_format == 'JPG':
            feedback.pushInfo(self.tr(f'JPEG quality: {jpeg_quality}'))
        feedback.pushInfo(self.tr(f'Output file: {output_file}'))

        # Create a rectangle from the extent
        rect = QgsRectangle(
            extent.xMinimum(),
            extent.yMinimum(),
            extent.xMaximum(),
            extent.yMaximum()
        )

        # Generate the SMP file
        generator = SMPGenerator(feedback)

        try:
            output_path = generator.generate_smp_from_canvas(
                rect, min_zoom, max_zoom, output_file,
                tile_format=tile_format, jpeg_quality=jpeg_quality
            )
        except (ValueError, OSError) as e:
            raise QgsProcessingException(str(e))

        # generate_smp_from_canvas returns None when the user cancelled.
        # Return an empty result dict so Processing surfaces it as cancelled,
        # not as a successful run with an empty output.
        if output_path is None:
            return {}

        # Return the results
        return {self.OUTPUT_FILE: output_path}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'generatesmp'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr('Generate SMP Map')

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'smp'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return ComapeoMapBuilderAlgorithm()
