name: Create Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get version from metadata.txt
        id: get_version
        run: |
          VERSION=$(grep "^version=" metadata.txt | cut -d'=' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create plugin package
        run: |
          mkdir -p comapeo_smp
          cp -r __init__.py comapeo_smp.py comapeo_smp_algorithm.py comapeo_smp_generator.py comapeo_smp_provider.py metadata.txt comapeo_smp/
          zip -r comapeo_smp_v${{ env.VERSION }}.zip comapeo_smp

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          files: comapeo_smp_v${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
